### PR TITLE
#79, Lexical argument shadows the dynamic variable

### PR DESCRIPTION
**Pull request by andreas-roehler**

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Thanks. But why do you want to rename `string`?

**Comment by andreas-roehler** [comment]
After all this warnings seems wrong in the very sense of term. However, 
might be useful not to name arguments like keywords or symbols used 
otherwise. So think the patch still makes sense.

**Comment by cpitclaudel** [comment]
> Assume the warning comes for this: 

That assumption is incorrect: variables and functions don't live in the same namespace, as ELisp is a Lisp 2.

Can you just run `M-x find-variable string`?

**Comment by andreas-roehler** [comment]
On 09.11.2017 15:02, Clément Pit-Claudel wrote:
>
>     Assume the warning comes for this:
>
> That assumption is incorrect: variables and functions don't live in 
> the same namespace, as ELisp is a Lisp 2.
>
> Can you just run |M-x find-variable string|?
>
>

string is a variable defined in ‘coq.el’.
Its value is nil

**Comment by cpitclaudel** [comment]
Thanks. That was a bug in proof general; it was fixed a while ago (by me ^^)
You can just update PG and you'll be good.

**Pull request closed without merging**
